[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "98uoSUVCBHRE6tJLrBozwnMCCnZbCYHmK9v5RTtY5dPv"
on_chain = "GJZsW2fuEFx7M83G7JNE6skGskJmK5KNe62ygoywJ6P4"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
keypair = "target/deploy/governance-keypair.json"  


[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
